version: '2.2'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
        container_name: elasticsearch
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms1024m -Xmx2048m"
            - discovery.type=single-node
            - TZ=Europe/London
            - xpack.security.enabled=true
            - xpack.license.self_generated.type=trial
        volumes:
            - data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic
        restart: on-failure

    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.4
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        volumes:
            - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        networks:
            - elastic

volumes:
    data01:
        driver: local

networks:
    elastic:
        driver: bridge