# Default Kibana configuration for docker target
server.name: kibana
server.host: "0"
elasticsearch.hosts: "http://elasticsearch:9200"
elasticsearch.username: elastic
elasticsearch.password: elastic
xpack.monitoring.ui.container.elasticsearch.enabled: true

# Dark Mode
uiSettings:
  overrides:
    "theme:darkMode": true   

