metricbeat.modules:

#------------------------------- System Module - no CPU -------------------------------
- module: system
  metricsets: ["load", "filesystem", "fsstat", "memory", "network", "process", "core", "diskio", "socket"]
  period: 10s
  enabled: true
  processes: ['.*']

  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

#------------------------------- System Module - CPU -------------------------------
- module: system
  metricsets: ["cpu"]
  period: 1s
  enabled: true

  cpu.metrics: [percentages, normalized_percentages, ticks]

#------------------------------- Docker Module -------------------------------
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s

#------------------------------- Nginx Module ---------------------------------

- module: nginx
  metricsets: ["stubstatus"]
  enabled: true
  period: 10s

  # Nginx hosts
  hosts: ["http://127.0.0.1:4200"]

  # Path to server status. Default server-status
  server_status_path: "server-status"

#------------------------------- MongoDB Module ---------------------------------

- module: mongodb
  metricsets: ["dbstats", "status", "collstats", "metrics", "replstatus"]
  period: 10s
  enabled: true
  hosts: ["mongo:27017"]
  username: admin
  password: admin

    
#========================== Elasticsearch output =============================
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: elastic

#============================== Kibana =========================================
setup.kibana:
  host: "kibana:5601"
  username: elastic
  password: elastic
  
#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here, or by using the `-setup` CLI flag.
setup.dashboards.enabled: true


#============================== Autodiscover =====================================

metricbeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: todolist-app_frontend
          config:
            - module: nginx
              metricsets: ["stubstatus"]
              hosts: "${data.host}:${data.port}"