#this.elk.docker v0.6.3
version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      cluster.name: "thiselkdocker"
      network.host: 0.0.0.0z
      xpack.license.self_generated.type: trial
      xpack.security.enabled: true
    environment:
      ELASTIC_PASSWORD: elastic
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      discovery.type: single-node
      TZ: Europe/London
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      elk:
    ports:
      - 9200:9200
    restart: on-failure

  kibana:
    image: kibana:7.8.0
    container_name: kibana
    hostname: kibana
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      TZ: Europe/London
    volumes:
      - ./configs/yaml/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - kibana:/usr/share/kibana/data
    networks:
      elk:
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: on-failure

  logstash:
    image: logstash:7.8.0
    container_name: logstash
    hostname: logstash
    environment:
      http.host: "0.0.0.0"
      xpack.monitoring.elasticsearch.hosts: "http://elasticsearch:9200"
      xpack.monitoring.elasticsearch.username: elastic
      xpack.monitoring.elasticsearch.password: elastic
      xpack.monitoring.enabled: true
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      TZ: Europe/London
      ELASTIC_PASSWORD: elastic
      ELASTIC_USERNAME: elastic
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./configs/driver:/usr/share/empty:ro
      - ./configs/plugin:/home
      - ./input/files:/usr/tmp:ro
      - ./input/database/mongo/temp:/opt:rw
    command: bash -c "bin/logstash-plugin install /home/logstash-input-mongodb-0.4.2.3.gem && logstash -f /usr/share/logstash/pipeline/logstash.conf"
    networks:
      elk:
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
    depends_on:
      - elasticsearch
    restart: on-failure

  filebeat:
    image: elastic/filebeat:7.8.0
    container_name: filebeat
    hostname: filebeat
    user: root
    volumes:
      - ./configs/yaml/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./input/logs:/var/log
      - /home/todolist-app/log/nginx/:/var/log/nginx
      - /home/todolist-app/log/mongo/:/var/log/mongo
    command: ["-strict.perms=false"]
    environment:
      TZ: Europe/London
    networks:
      elk:
    depends_on:
      - elasticsearch
      - kibana
    restart: on-failure

  metricbeat:
    image: elastic/metricbeat:7.8.0
    container_name: metricbeat
    hostname: metricbeat
    user: root
    volumes:
      - /:/hostfs:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/yaml/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
    command:
        -e 
        --strict.perms=false
        -system.hostfs=/hostfs
    environment:
      TZ: Europe/London
      ELASTIC_PASSWORD: elastic
      ELASTIC_USERNAME: elastic
    networks:
      elk:
    depends_on:
      - elasticsearch
      - kibana
    restart: on-failure

  logspout:
    image: bekt/logspout-logstash
    container_name: logspout
    hostname: logspout
    environment:
      ROUTE_URIS: logstash://logstash:5000
      TZ: Europe/London
      ELASTIC_PASSWORD: elastic
      ELASTIC_USERNAME: elastic
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      elk:
    depends_on:
      - logstash
    restart: on-failure


networks:
  elk:
    driver: bridge


volumes:
  elasticsearch:
    driver: local
  kibana:
    driver: local

